---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:  
  name: traffictargets.access.smi-spec.io
spec:  
  group: smi-spec.io
  version: v1alpha1
  scope: Namespaced 
  names:    
    kind: TrafficTarget
    shortNames: 
      - tt
    plural: traffictargets
    singular: traffictarget

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:  
  name: identitybindings.access.smi-spec.io
spec:  
  group: smi-spec.io
  version: v1alpha1
  scope: Namespaced 
  names:    
    kind: IdentityBinding
    shortNames: 
      - ibs
    plural: identitybindings
    singular: identitybinding

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:  
  name: httproutegroups.spec.smi-spec.io
spec:  
  group: smi-spec.io
  version: v1alpha1
  scope: Namespaced 
  names:    
    kind: HTTPRouteGroup
    shortNames: 
      - htr
    plural: httproutegroups
    singular: httproutegroup

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:  
  name: tcproutes.smi-spec.io
spec:  
  group: smi-spec.io
  version: v1alpha1
  scope: Namespaced 
  names:    
    kind: TCPRoute
    shortNames: 
      - tr
    plural: tcproutes
    singular: tcproute
