
# Define a ServiceAccount for Service A
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-a
automountServiceAccountToken: false

# Define a ServiceAccount for Service B
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-b
automountServiceAccountToken: false

# Create a pod for service-a
---
apiVersion: v1
kind: Pod
metadata:
  name: service-a
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
    "consul.hashicorp.com/connect-service": "service-a"
  labels:
    app: service-a
spec:
  serviceAccountName: service-a
  automountServiceAccountToken: true
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent

# Create a pod for service-b
---
apiVersion: v1
kind: Pod
metadata:
  name: service-b
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
    "consul.hashicorp.com/connect-service": "service-b"
  labels:
    app: service-b
spec:
  serviceAccountName: service-b
  automountServiceAccountToken: true
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
