---
apiVersion: smi-spec.io/v1alpha1
kind: TCPRoute
metadata:
  name: tcp-route

---
kind: TrafficTarget
apiVersion: smi-spec.io/v1alpha1
metadata:
  name: foo
  namespace: default
selector:
  matchLabels:
    app: foo
port: 8080
rules:
- kind: TCPRoute
  name: tcp-route

---
kind: IdentityBinding
apiVersion: smi-spec.io/v1alpha1
metadata:
  name: account-specific
  namespace: default
subjects:
- kind: ServiceAccount
  name: bar
  namespace: default
targetRef:
  kind: TrafficTarget
  name: foo 

