# TCPRoute for Service A 
---
apiVersion: specs.smi-spec.io/v1alpha1
kind: TCPRoute
metadata:
  name: service-a-tcp-route

# TrafficTarget defines allowed routes for service-a
# In this example service-b is allow to connect using
# TCP
---
kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha1
metadata:
  name: service-a-targets
  namespace: default
destination:
  kind: ServiceAccount
  name: service-a
  namespace: default
sources:
- kind: ServiceAccount
  name: service-b
  namespace: default
specs:
- kind: TCPRoute
  name: service-a-tcp-route
