---
# Source: consul/templates/connect-inject-authmethod-clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consul-consul-connect-injector-authmethod-authdelegator-role-binding
  labels:
    app: consul
    chart: consul-helm
    heritage: Tiller
    release: consul
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "system:auth-delegator"
subjects:
  - kind: ServiceAccount
    name: consul-consul-connect-injector-authmethod-svc-account
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consul-consul-connect-injector-authmethod-serviceaccount-role-binding
  labels:
    app: consul
    chart: consul-helm
    heritage: Tiller
    release: consul
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: consul-consul-connect-injector-authmethod-role
subjects:
  - kind: ServiceAccount
    name: consul-consul-connect-injector-authmethod-svc-account
    namespace: default
