---
# Source: consul/templates/server-clusterrole.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consul-consul-server
  labels:
    app: consul
    chart: consul-helm
    heritage: Tiller
    release: consul
