---
# Source: consul/templates/server-clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consul-consul-server
  labels:
    app: consul
    chart: consul-helm
    heritage: Tiller
    release: consul
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: consul-consul-server
subjects:
  - kind: ServiceAccount
    name: consul-consul-server
    namespace: default
