---
# Source: consul/templates/server-acl-init-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: consul-consul-server-acl-init
  namespace: default
  labels:
    app: consul
    chart: consul-helm
    heritage: Tiller
    release: consul