---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: smi-controller
  labels:
    # Add these permissions to the "view" default role.
    rbac.authorization.k8s.io/aggregate-to-view: "true" 
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true" 
rules:
- apiGroups: ["specs.smi-spec.io", "access.smi-spec.io",""] 
  resources: ["tcproutes","htttproutegroups","traffictargets","events"] 
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: smi-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: smi-controller
subjects:
- kind: ServiceAccount
  name: smi-controller
  namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: smi-controller
  namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-smi-controller-deployment
  labels:
    app: consul-smi-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-smi-controller
  template:
    metadata:
      labels:
        app: consul-smi-controller
    spec:
      serviceAccountName: smi-controller
      automountServiceAccountToken: true
      containers:
      - name: consul-smi-controller
        image: hashicorp/consul-smi-controller:v0.0.0-alpha.1
        imagePullPolicy: IfNotPresent
        command: ['/app/smi-controller']
        args: ["--consul-http-addr=http://$(HOST_IP):8500", "--consul-http-token=$(CONSUL_HTTP_TOKEN)"]
        env:
        - name: CONSUL_HTTP_TOKEN
          valueFrom:
            secretKeyRef:
              name: consul-smi-acl-token
              key: token
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
