version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.7
   
    environment:
      GO111MODULE: "on"
    
    working_directory: /go/src/github.com/hashicorp/consul-smi-controller
    
    steps:
      - checkout

      - run: 
          name: build application
          command: GO_ENABLED=0 GOOS=linux go build -o bin/smi-controller .

      - run: 
          name: test application
          command: go test -v --race ./...
      
      - persist_to_workspace:
          root: /go/src/github.com/hashicorp
          paths:
            - consul-smi-controller


  release:
    docker:
      - image: circleci/golang:1.12.7
   
    working_directory: /go/src/github.com/hashicorp/consul-smi-controller
    
    steps:
      - attach_workspace:
          at: /go/src/github.com/hashicorp

      - setup_remote_docker

      - run: 
         name: docker login
         command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}

      - run: 
          name: create docker container
          command: docker build -t hashicorp/consul-smi-controller:${CIRCLE_TAG} .

      - run:
          name: push to docker hub
          command: docker push hashicorp/consul-smi-controller:${CIRCLE_TAG}

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
