---
# Source: consul/templates/connect-inject-authmethod-clusterrole.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consul-consul-connect-injector-authmethod-role
  labels:
    app: consul
    chart: consul-helm
    heritage: Tiller
    release: consul
rules:
  - apiGroups: [""]
    resources:
      - serviceaccounts
    verbs:
      - get
