---
# Source: consul/templates/connect-inject-authmethod-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: consul-consul-connect-injector-authmethod-svc-account
  namespace: default
  labels:
    app: consul
    chart: consul-helm
    heritage: Tiller
    release: consul
